# -*- yaml -*-
application: codeherenow
version: 1
threadsafe: false
api_version: 1
default_expiration: 1d

# ideally python27 but tweepy is incompatible. :/
runtime: python

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(ticker|search_recent_events|events_near)
  script: search.py

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
# don't need anything in the tweepy or webapp-improved subdirs, especially since
# webapp-improved/lib/ has over 1k files!
- ^tweepy_submodule/(docs|examples|tools)/.*
- ^webapp-improved/.*/.*
